include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-apcontroller
PKG_VERSION:=20260111
PKG_RELEASE:=304
LUCI_TITLE:=LuCI application for apcontroller
LUCI_DEPENDS:=+apcontroller
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
